<?

// module to resource mapping

$RESOURCEMAPPING = array();

$resource = 'Applications';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'AuditTrail';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'Company';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'CompanyAddresses';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'CompanyFaxNumbers';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'CompanyLogos';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'CompanyPhoneNumbers';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'Contact';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'Countries';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'Currencies';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'CustomFields';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'CustomFieldValues';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'DateFormats';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'EmailAddresses';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'Employment';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'EmploymentJobTitle';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'EmploymentStatus';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'GeneralSettings';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'Languages';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'Modules';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'Organization';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'PaperSizes';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'Permissions';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'PhoneNumbers';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'PublicDocuments';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'Roles';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'TimeFormats';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'TimeZones';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'Users';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

$resource = 'Zones';
$modulesToMap = array();
array_push( $modulesToMap, 1 );
array_push( $modulesToMap, 2 );
array_push( $modulesToMap, 3 );
array_push( $modulesToMap, 4 );
array_push( $modulesToMap, 5 );
array_push( $modulesToMap, 6 );
array_push( $modulesToMap, 7 );
array_push( $modulesToMap, 8 );
array_push( $modulesToMap, 9 );
array_push( $modulesToMap, 10 );
array_push( $modulesToMap, 11 );
array_push( $modulesToMap, 12 );
array_push( $modulesToMap, 13 );
array_push( $modulesToMap, 14 );
array_push( $modulesToMap, 15 );
array_push( $modulesToMap, 16 );
array_push( $modulesToMap, 17 );
array_push( $modulesToMap, 18 );
array_push( $modulesToMap, 19 );
array_push( $modulesToMap, 20 );
array_push( $modulesToMap, 21 );
array_push( $modulesToMap, 22 );
array_push( $modulesToMap, 23 );
array_push( $modulesToMap, 24 );
array_push( $modulesToMap, 25 );
array_push( $modulesToMap, 26 );
array_push( $modulesToMap, 27 );

$RESOURCEMAPPING[ $resource ] = $modulesToMap;

unset( $resource );
unset( $modulesToMap );
define( 'RESOURCEMAPPING', serialize( $RESOURCEMAPPING ) );